<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net6.0;net8.0;net9.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net48' Or '$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net9.0'">
    <DefineConstants>$(DefineConstants);HARPOS7_LEGACY_AUTH</DefineConstants>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject />
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="zlib.net-mutliplatform" Version="1.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="PolySharp" Version="1.15.0" PrivateAssets="all" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="System.Threading.Channels" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="runtimes\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>true</Pack>
      <PackagePath>runtimes/</PackagePath>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Remove="runtimes\info.txt" />
  </ItemGroup>
  <ItemGroup>
    <None Include="build\net8.0\CopyNativeFiles.targets" Pack="true" PackagePath="build\net8.0\DotNetProjects.S7CommPlusDriver.targets" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="runtimes\linux-x64\" />
    <Folder Include="runtimes\osx-x64\" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net48' Or '$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net9.0'">
    <PackageReference Include="HarpoS7">
      <Version>1.1.4</Version>
    </PackageReference>
    <PackageReference Include="HarpoS7.PublicKeys">
      <Version>1.1.4</Version>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup>
    <AssemblyTitle>S7CommPlusDriver</AssemblyTitle>
    <Product>S7CommPlusDriver</Product>
    <Copyright>Copyright (c) 2025, DotNetProjects, Thomas Wiens</Copyright>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>DotNetProjects.$(AssemblyName)</Title>
    <PackageId>DotNetProjects.$(AssemblyName)</PackageId>
    <Company>DotNetProjects</Company>
    <PackageProjectUrl>https://github.com/dotnetprojects/S7CommPlusDriver</PackageProjectUrl>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
</Project>
